# Generated by Django 5.1 on 2024-08-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField(blank=True, null=True)),
                ('glucose', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skin_thickness', models.IntegerField(blank=True, null=True)),
                ('insulin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('diabetes_pedigree_function', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('outcome', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
