# Generated by Django 5.1 on 2024-08-30 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
