# Generated by Django 5.1 on 2024-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='user id '),
        ),
    ]
